### ISSUE TITLE
Incompatibility with PIX GPU captures

### ISSUE THREAD

**Issue by axiagame** [MolecularMatters/lpp_public#13]
Hello :-)

PIX DLLs cannot load when live++ is active, preventing me to do GPU captures using PIX API

Steps to repro:
- Load Live++ DLLs
- Load PIX DLLs
- Use PIX API to make a GPU capture => will fail (cannot load specific DLL HRESULT returned)

It also happens if PIX DLLs are loaded first.

Thanks for your time ^^

**Comment by MolecularMatters** [comment]
Hello,

This sounds very similar to a previous issue regarding OBS hooks: https://github.com/MolecularMatters/lpp_public/issues/9#issuecomment-1954831343

Though I'm wondering why this would happen when PIX DLLs are loaded first as well.
Do you know what happens underneath when trying to make a GPU capture using the PIX API? Does PIX try to hook functions at that time? If so, it likely won't find any unused address space in the +-2GB range surrounding the executable because that is reserved by Live++.

I was under the impression that loading the PIX DLL first would do the following:
- Load the PIX DLL
- Reserve address space next to the D3D/Vulkan/whatever API to be hooked at a later point in time by PIX
- Load the Live++ DLL and enable some module(s)

If so, PIX should work as is.

**Comment by axiagame** [comment]
Hello :-)

Following the tips in linked issue fixed the problem for us. So this is not an issue any more!

Thanks a lot for your help :-)
